### ISSUE TITLE
[ Week 6 ] 6주차 워크북 미션

### ISSUE THREAD

**Issue by 7beunseo** [DS-UMC-7th/UMC-7th-Noeul#4]
### 🛠 Mission

2주차 미션 때 했던 해당 화면들에 대해 작성했던 쿼리를 QueryDSL로 작성하여 리팩토링하기

### 📝 To-do

- [x] QueryDSL 기본 설정
- [x] Q 클래스 생성
- [x] QueryDSL 설정파일 만들기
- [x] 더미 데이터 생성 
- [x] QueryDSL 쿼리 작성
- [x] 작동 확인

### 🔍 접근 방법

.
